name: FastAPI CI

on:
    push:
        branches: [ "main","deveop" ]
        paths:
            - "src/api**"
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:

    build: 
        uses: ./.github/workflows/api-code-check.yml
        secrets: inherit

    build-and-push:
        uses: ./.github/workflows/api-build-and-push.yml
        secrets: inherit
        permissions:
            contents: read
            packages: write
        if: github.ref == 'refs/heads/main'
        with:
            tag_name: latest
    
    deploy:
        needs: build
        if: github.ref == 'refs/heads/main'
        uses: ./.github/workflows/api-deploy.yml
        with:
            tag_name: latest
        secrets: inherit
